入力した文字をconsole.logに表示する
shiory602/Sushi pull request #2
Opened 2021-03-05 22:54 UTC by shiory602

2021-03-05 23:15 UTC, ginpei requested changes
ちょっと修正してもらって、あと git の話とか `README.md` に書いておいてください。

2021-03-05 23:15 UTC, ginpei commented on 20210305/index.html
> +				event.preventDefault();
この `event` は `window.event` です。グローバル変数は管理が被ったりして問題になりやすいので避けるべきです。

今回は代わりに引数で受け取れます。それを使ってください。

```diff
- form.addEventListener("submit", () => {
+ form.addEventListener("submit", (event) => {
```

2021-03-05 23:15 UTC, ginpei commented on 20210305/index.html
> +					msg.innerHTML = "Write a message please :)";
こういう風にちゃんとエラー出すの良いですね。大事です。

2021-03-05 23:16 UTC, ginpei commented on 20210305/index.html
> +					msg.innerHTML = "Write a message please :)";
あ、ここは特に修正ないので読んだら Resolve conversation して終わりにしてください。

2021-03-06 09:58 UTC, shiory602 commented on 20210305/index.html
> +				event.preventDefault();
修正とREADMEへの記述完了しました。

2021-03-06 18:42 UTC, ginpei approved these changes
LGTM

2021-03-06 18:46 UTC, merged