編集小窓機能をつける
shiory602/Sushi pull request #8
Opened 2021-03-20 07:02 UTC by shiory602

2021-03-24 06:21 UTC, ginpei requested changes
コードの変更と抜き出しは別のPRにしてください。比較が意味をなさず、変更箇所を判断しづらくなってしまいます。（次回以降お願いします。）

あと編集機能、2人目以降で動いてないです。編集機能の中で、編集対象をどうにかして探す必要があります。ヒントが必要ならまた聞いてください。

ちなみにひとつでは動くけど複数件になると駄目、というのはよく出る不具合なので今後注意してください。良い体験でしたね！

2021-03-24 06:21 UTC, ginpei commented on 20210319/css/style.css
> +		* {
インデントがアレです

2021-03-24 06:21 UTC, ginpei commented on 20210319/js/main.js
> +	li.innerHTML = `<p id="nameItem" onclick="nameFunction('${names.value}')">${names.value}</p>(<span id="ageItem" onclick="ageFunction('${age.value}')">${age.value}</span>)`;
そうですね、こんな感じでそれぞれ要素を用意してやる感じですね 👍

2021-03-24 06:21 UTC, ginpei commented on 20210319/js/main.js
> +function nameFunction(e) {
関数名、引数名ともに意味のある命名にしてください

2021-03-24 06:21 UTC, ginpei commented on 20210319/js/main.js
> +    document.getElementById("nameItem").innerText = personName;
`getElementById()` はIDで検索して最初の1件を返します。このコードだと2人目以降が変更できません。

なにかうまいやりかた思いついたら偉いです。

2021-03-28 17:07 UTC, shiory602 commented on 20210319/js/main.js
> +function nameFunction(e) {
eをそれぞれname/ageに変更しました。

2021-03-30 20:12 UTC, ginpei commented on 20210319/js/main.js
> +    document.getElementById("nameItem").innerText = personName;
@shiory602 放置しててすみません。イベントリスナー関数の `event.currentTarget` を使うと、利用者が操作を行った対象の要素を得ることができます。これ使うと諸々便利です。

https://codepen.io/ginpei/pen/RwKoxgr

ところで `querySelector()` は `document` だけじゃなくて要素からも利用可能です。`li = document.createElement("li")` の後、 `elName = li.querySelector('.nameItem')` みたいに使えます。そしたら `elName.addEventListener()` できます。

2021-03-31 18:06 UTC, shiory602 commented on 20210319/js/main.js
> +    document.getElementById("nameItem").innerText = personName;
ヒントありがとうございます！
`event.currentTarget`と`querySelector()`使ってみました。
先ほど完成しましたのでチェックお願いします！！

2021-04-03 05:40 UTC, ginpei requested changes
修正お願いします。もうちょっと！

2021-04-03 05:40 UTC, ginpei commented on 20210311/README.md
> +// [1,2,3,4,5,6,7]
JSの `arr.sort()` は歴史的経緯によりぶっ壊れているので、必ず比較関数 _comparator_ を与えてください。

```js
// Don't 👎
arr = [1, 2, 3, 11, 22, 111];
arr.sort();
// [1, 11, 111, 2, 22, 3]
```

```js
// Do 👍
arr = [1, 2, 3, 11, 22, 111];
arr.sort((v, u) => v - u);
// [1, 2, 3, 11, 22, 111]

arr = ["û", "ú", "ù", "ü"];
arr.sort((v, u) => v.localeCompare(u));
// ["ú", "ù", "û", "ü"]
```

今回の実装では関数は与えられていますね。でも年齢で 7 歳と 20 歳、60 歳ではどう並ぶべきでしょうか？　うまく動いてないので見直してみてください。（前回見落としてました。）

2021-04-03 05:40 UTC, ginpei commented on 20210319/README.md
> +### Chips
それはポテチ

- [chips - Google Search](https://www.google.com/search?q=chips&tbm=isch)
- [tips and tricks - Google 検索](https://www.google.com/search?q=tips+and+tricks)

2021-04-03 05:40 UTC, ginpei commented on 20210319/js/main.js
> +		personsName = prompt("You can edit the name here!", elName.textContent);
これだと2度目もキャンセルしたとき空欄になっちゃいますね。

聞きなおさず、更新しないで終了でも良いのでは？　聞きなおしたい場合はもう一工夫必要です。

2021-04-03 05:40 UTC, ginpei commented on 20210319/js/main.js
> +	let elName = li.querySelectorAll("#elName");
作成した `li` 配下にはひとつの `#elName` しかないはずなので、`li.querySelector()` を使う方が簡単です。

2021-04-03 05:40 UTC, ginpei commented on 20210319/js/main.js
> +	if (elName) {
この条件は不要

2021-04-03 19:18 UTC, shiory602 commented on 20210311/README.md
> +// [1,2,3,4,5,6,7]
チェックありがとうございます！
`let sortDesc = (a, b) =>  b.key.localeCompare(a.key);`
このようにファンクションを作っていたんですがうまく動いてなかったようです。
```JS
let sortDesc = (a, b) => {
	return b.key - a.key;
}
```
このように変更したらちゃんと順番に並びました！
`.localeCompare()`が文字列用のソートで`v - u`が数字用という認識であってますか？

2021-04-03 21:05 UTC, shiory602 commented on 20210319/js/main.js
> +		personsName = prompt("You can edit the name here!", elName.textContent);
更新なしの終了にしました！

2021-04-04 03:44 UTC, ginpei commented on 20210311/README.md
> +// [1,2,3,4,5,6,7]
だいたい合ってますが、`v`, `u` が数値であるという前提です。

数値 `123` と数字（文字列） `"123"` を混同しないように気を付けてください。`1+1` は `2` になりますが、`"1" + "1"` は `"11"` になります。まあ実際引き算は動くんですけどねー。

ちなみに `<input type="number">` の場合は `el.value` の代わりに `el.valueAsNumber` が利用できます。

```html
<input id="elText" type="text" value="123" />
<input id="elNumber" type="text" value="123" />
```

```js
elText.value // => "123"
elText.valueAsNumber // => NaN
elNumber.value // => "123"
elNumber.valueAsNumber // => 123
```

2021-04-04 06:38 UTC, shiory602 commented on 20210319/js/main.js
> +	let elName = li.querySelectorAll("#elName");
`li.querySelector()`にしたところ forEachにエラー（not a function）が発生してしまったため`li.querySelectorAll()`に戻しました。こちらだとエラーが出ません！

2021-04-04 06:47 UTC, ginpei commented on 20210319/js/main.js
> +	let elName = li.querySelectorAll("#elName");
ひとつしかないので `forEach()` で繰り返しにする必要がないです

2021-04-04 06:52 UTC, shiory602 commented on 20210319/js/main.js
> +	let elName = li.querySelectorAll("#elName");
おっしゃる通りでした！
教えてくれてありがとうございます。

2021-04-04 06:56 UTC, shiory602 commented on 20210311/README.md
> +// [1,2,3,4,5,6,7]
ややこしいですけどそうなんですね。。
勉強になります！ありがとうございます😃

2021-04-06 16:52 UTC, ginpei approved these changes
LGTM

2021-04-06 16:52 UTC, ginpei commented on 20210311/README.md
> +If you want to sort `String`, use `arr.sort((v, u) => v.localeCompare(u));`
細かい話っぽいですが `String` はコンストラクター関数、`string` は型、という違いがあります。文章なら良いけどコード上だと別物なので気を付けてください。

2021-04-06 16:52 UTC, ginpei commented on 20210311/README.md
> +### Tips💡
ポテチおいしかったですね

2021-04-06 17:06 UTC, ginpei commented
次は情報を保存するようにしてみましょう。

- 画面読み込み時の最初の処理で保存されていた情報を読み込み、一覧を再構築する
- 更新があるたびに情報を上書き保存する

この API が使えます。

- 保存 https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
  - 保存 `window.localStorage.setItem('message', 'Hello World!')`
  - 取得 `message = window.localStorage.getItem('message')`
- 保存用に情報変形 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON
  -  オブジェクト→文字列 `json = JSON.stringify([{ name: "Alice", age: 12 }])`
  - 文字列→オブジェクト `data = JSON.parse(json)`

DevTools のコンソールとかで試してみてください。画面を再読み込みしても情報が保存されています。

```js
KEY = 'super-cool-data';

// 保存
data = [{ name: "Alice", age: 12 }];

json = JSON.stringify(data);
window.localStorage.setItem(KEY, json);

// 取得
json = window.localStorage.getItem(KEY);
data = JSON.parse(json);
```

これとあともうひとつやったら一段落してReactの話をしたいかなと思ってます。（何か思い出さなければ。）　よろしくお願いします。

2021-04-06 19:03 UTC, shiory602 commented on 20210311/README.md
> +### Tips💡
美味しかったです🤤

2021-04-06 19:08 UTC, merged